### ISSUE TITLE
"The given reference cannot be used because the chromosome names are inconsistent!"

### ISSUE THREAD

**Issue by SunDionel** [raphael-group/hatchet#1]
I am getting the error during deBAF. I am using the same reference that I've used for alignment.

**Comment by simozacca** [comment]
The error indicates that deBAF found an inconsistency in the names of the chromosomes between the reference genome and the BAM files. HATCHet currently has two requirements:
1. The names of the chromosomes in the reference genome need to strictly follow the FASTA format so the header of every chromosome needs to contain only the name of the chromosome without any white space or any other label after the symbol ">", e.g. >chr1, >chr2, ... or >1, >2, ...
2. The name of the selected chromosomes between the reference genome and the BAM files must be identical.

In order to debug this issue please provide the results of the following commands, assuming that you have `samtools` in `PATH` (otherwise simply use the full path to samtools), ${REF} is the full path to the reference genome, ${NORMAL} is the full path to the normal BAM, and ${BAMx} is the full path to any tumor-sample BAM x:

1. grep -e "^>" ${REF} : this gives the names of all chromosomes in the reference genome

2. samtools view -H ${NORMAL} : this gives the names of all chromosomes in the normal BAM

3. samtools view -H ${BAMx} : this gives the names of all chromosomes in the tumor-sample BAM x (execute this for every sample x)

**Comment by SunDionel** [comment]
Thank you for the detailed answer. The problem was solved when I removed some labels from the chromosome names in the reference.

**Comment by simozacca** [comment]
I close the issue for now, please feel free to re-open it if you have further issues

**Comment by vyellapa** [comment]
@SunDionel how did you resolve this error?
The same ref was used for aligning the bams, yet Im getting this error.

Did you remove this part "dna:chromosome chromosome:GRCh37:1:1:249250621:1" from contig names?
>1 dna:chromosome chromosome:GRCh37:1:1:249250621:1
>2 dna:chromosome chromosome:GRCh37:2:1:243199373:1

**Comment by vyellapa** [comment]
In ArgParsing.py this should work for most fastas
stdout, stderr = subprocess.Popen("grep -e \"^>\" {}| cut -d' ' -f1".format(reference), stdout=subprocess.PIPE, shell=True).communicate()

**Comment by simozacca** [comment]
This is indeed a good correction which automatically removes additional labels from chromosome's names in the provided reference, thank you!

I will make sure everything will continue to work properly and I will include a slightly modified version which also considers tabs, i.e.

```python
stdout, stderr = subprocess.Popen("grep -e '^>' {} | awk '{ print $1 }' ".format(reference), stdout=subprocess.PIPE, shell=True).communicate()
```

**Comment by simozacca** [comment]
I re-open the issue until the integration of the command is completed and tested.

**Comment by simozacca** [comment]
A correction for this issue has been fully included in current implementation. Now any additional string in the chromosome ID will be discarded and the only required is that the first word (either separated by space of tabs) is exactly the name of the chromosome.

I close the issue for now but please feel free to re-open in case of additional issues.

**Comment by rgold97** [comment]
Do you have any advice on this issue if my reference looks like this:
![image](https://user-images.githubusercontent.com/28493357/108802300-f35c6f00-7565-11eb-8ee3-51fc217508c7.png)

I also was getting an error message in the SNPCaller function that seems to be related:
![image](https://user-images.githubusercontent.com/28493357/108802374-1e46c300-7566-11eb-8ad4-b9d8bab1335c.png)

Lastly, a warning message that "The index file is older than the data file" kept popping up. 

Any advice would be greatly appreciated!! Thank you!

**Comment by simozacca** [comment]
Could you please confirm that this is the same reference genome used for the alignment of the sequencing reads in you BAM files? In particular, could you please confirm that your BAM files have not been aligned to a reference genome whose chromosomes have the `chr`-name notation? On this regard, please provide the output of the following commands for both the matched-normal BAM file `$NOR` and a tumour BAM file `$TUM`:

```shell
samtools view -H $NOR
```
```shell
samtools view -H $NOR
```

**Comment by rgold97** [comment]
Thanks for your help!
Yes it should be the same reference genome that was used to align the reads in the BAM. Pretty sure the BAMs do not have the chr-name notation, but with "SN:1-22/XY" notation instead. 

Here is the (top of the) output from samtools view -H $NOR:
<img width="1176" alt="Screen Shot 2021-02-24 at 9 46 58 AM" src="https://user-images.githubusercontent.com/28493357/109017537-45e07d00-7685-11eb-9dc3-c0fe34b36eb7.png">

And samtools view -H $TUM
<img width="1176" alt="Screen Shot 2021-02-24 at 9 52 48 AM" src="https://user-images.githubusercontent.com/28493357/109018375-0fefc880-7686-11eb-98d4-a5c59bb94eaa.png">

Any advice would be very helpful! Thanks.

**Comment by simozacca** [comment]
@vineetbansal Might this be some error in the new code that performs this check? For example, if a chromosome is `>1 blabla` in the reference genome do we still only extract `1` right?
