### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by kristianunger** [raphael-group/hatchet#104]
Hi there,

I am running the full pipeline on WES profiles with the settings recommended in the template ini file on a Slurm cluster using 8 cpus with 32GB each. The runs with Gurobi or CBC solvers seem to take forever while the process goes relatively quick until solving the best cluster solution "## Running diploid with 5 clones". The pipeline got stuck at this state since more than 48h or so. Can you give a recommendation what could be done in order to speed up the process? Would increasing the number of cpus have a significant effect?

Many thanks,

Kristian

**Comment by simozacca** [comment]
Thank you for your feedback. First of all, could you please confirm that the performance issues are observed even when using Gurobi? Also, could you please clarify if you are using the standard version or if you are manually changing the solver? While slower performance might be common with CBC as it is a slower solver, Gurobi should reflect the state of the art and the observed times are particularly strange.

One first issue might be the use of an extremely high maximum copy number, could you please try to fix the maximum diploid copy number to something like 8, and the maximum tetraploid copy number to something like 16? Please let us know if this results in a change of performance.

**Comment by kristianunger** [comment]
Thanks. I confirm both - Gurobi and standard version. I will try with the hints you gave me and let you know how it goes.

**Comment by kristianunger** [comment]
Hi there! Sorry for not getting back. I actually had an error in my Gurobi configuration. Having corrected this, all worked quite well. Processing time for a 100x WES normal, tumor, relapse triplet was about 2h.

**Comment by simozacca** [comment]
This is great! Could you please share your issue with Gurobi configuration and related fix so that other people from the community could benefit in the future?

In the meanwhile, I am closing the issue, but please feel free to re-open it in case of need.

**Comment by miachom** [comment]
Hi, I am running HATCHet v1.1.2 on example data and my own data using glpk and cbc both to test. However, I seem to also face a similar problem where both these solvers seem are taking more > 72 hrs while the process is quick until "Running diploid with 3 clones". Unfortunately, I can't get an academic Gurobi license so I have to use either cbc or glpk. Other than this, I don't see any errors in log. Can you recommend what I can do to speed up the process? I also ran `hatchet check-solver` which says `solver check FAILED`. But I am assuming this could be because I am not using Gurobi. What can I do in such a situation?
