### ISSUE TITLE
clusters are not separated

### ISSUE THREAD

**Issue by asangphukieo** [raphael-group/hatchet#114]
Hi,

I tried running HATCHet with my 3 tumor samples and matched-normal.
I found that the clusters are not very clear separated as in figure below
![image](https://user-images.githubusercontent.com/47389288/150333771-cabd76e5-10d4-4f62-bf9b-06d82d90f6a8.png)

Then, I tried adjusting -tB and -tR parameters in range of 0.01 - 0.20, but the results are the same.
Could you please give me suggestion to separate the clusters? 

Regards,
Apiwat

**Comment by simozacca** [comment]
Thank your for your feedback!

Before evaluating how well separated your clusters are, I think that we need to fix a scaling issue in this 2D plot. In fact, due to the presence of few outliers the y-axis (RDR) seems to be out of scale and it does not allow us to properly see the RDR values for most of the genomic regions (which have RDR <2). Therefore, I would suggest to try to fix a maximum y-axis value to fix the out-of-scale issue and then re-evaluate the clustering: this can be achieved using the flag `--ymax` (please note that flags `--ymin`, `--xmax`, and `--xmin` are also similarly available) and for example using
```
--ymax 2.5
```
Could you please try this option and post the updated results?

**Comment by asangphukieo** [comment]
Hi simozacca,

Thank you for your suggestion.
Yes, the graph looks really better now!

![image](https://user-images.githubusercontent.com/47389288/150370212-966b4774-c4bf-43de-8d0e-2732e6cf13f0.png)

However, one of my samples still are not separated.


![image](https://user-images.githubusercontent.com/47389288/150370285-15b1ef1a-2c74-44d7-bf21-399ebf1e9bfe.png)

Please give me any suggestion to separate the clusters?

**Comment by simozacca** [comment]
I am afraid your clusters are simply not separated, especially in the sample at the bottom. In particular, the sequencing signals from your data indicate that tumour purity might be too low, especially in the second sample. HATCHet allows the analysis of low tumour purity samples by jointly leveraging the signal from higher-purity samples, but in this case you do not have high tumour purity samples and the tumour purity seems to be too low anyway for accurate copy number analysis.
