### ISSUE TITLE
Python 3 support???

### ISSUE THREAD

**Issue by pkMyt1** [raphael-group/hatchet#12]
Since Python 2 is gone will there be support for Python 3?  I have started to make the changes for Python 3 support but I did it using a clone of master but I see a Ci branch that appears to be active.  Is someone already working on this?  I don't want to duplicate efforts.

**Comment by simozacca** [comment]
Yes, the transition to Python 3 is scheduled and in progress on the CI branch: @vineetbansal is working on this and it should be successfully completed. However, we cannot release the transition to Python 3 yet because HATCHet depends on [bnpy](https://github.com/bnpy/bnpy) which currently only supports Python 2. `bnpy` is also currently transitioning to Python 3 and the estimated date for this transition is at the end of September (the information is from private communications). Thus, we will only be able to complete such transition after that.

In any case, the support for Python 2 ended but this does not affect the stability of HATCHet: the support and the compatibility for the current version of HATCHet is guaranteed by using python environments, e.g. [virtualenvs](https://docs.python-guide.org/dev/virtualenvs/) or [conda](https://docs.conda.io/en/latest/), as currently suggested in the documentation.

If you would like to know more details about the progress of `bnpy` transition to Python, please contact the authors of `bnpy` directly on the related [issue](https://github.com/bnpy/bnpy/issues/4).

**Comment by pkMyt1** [comment]
Thank you.  I will check with the bnpy folks.  We don't use Python 2 here and I will need to setup an virtual env just for HATCHet.  While certainly doable, not something I really want to mess with for single case.  Will keep an eye on your progress.
