### ISSUE TITLE
Reference Index File Name

### ISSUE THREAD

**Issue by pkMyt1** [raphael-group/hatchet#14]
Looks like HATCHet requires the reference index file to end in a .dict.  This doesn't follow the standard convention of .fai or, sometimes, .tbx for the index files.  Is there a need in your pipeline for the .dict name?  FAIDX automatically adds the .fai extnsion

**Comment by simozacca** [comment]
For the reference genome, HATCHet requires the existence of a a sequence dictionary (`.dict`), which is part of all standard pipelines for sequencing data, see for example [GATK](https://gatk.broadinstitute.org/hc/en-us/articles/360035531652-FASTA-Reference-genome-format) or [Galaxy](https://galaxyproject.org/admin/data-preparation/). Please note that the sequence dictionary is **NOT** the reference index `.fai`, which is a different structure, has a different function, and it is also recommended.

The dictionary of a reference genome is often included in the available bundles for the reference genomes, see the example for hg19 from the Broad at ftp://gsapubftp-anonymous@ftp.broadinstitute.org/bundle/hg19. However, the dictionary can also be generated in seconds using either [SAMtools](http://www.htslib.org/doc/samtools-dict.html) or [Picard tools](https://gatk.broadinstitute.org/hc/en-us/articles/360036729911-CreateSequenceDictionary-Picard-). We will add these details and links to the documentation.

Please note that the dictionary is fundamental to retrieve the length of the chromosomes, and it is especially important since HATCHet also supports non-human reference genomes, see https://github.com/raphael-group/hatchet/issues/6.

**Comment by pkMyt1** [comment]
Thanks.  I haven't found the GATK pipelines to be terribly useful for what we do so have never used the dictionary.  All the same information is in the index just a different format, minus the checksum.  As long as you know what species the information can be extracted.  Will create a dictionary and see what happens.

**Comment by vineetbansal** [comment]
In case it helps, we're generating the `.dict` file from the `.fai` file for CI purposes using the command:
```
samtools view -H -ht hg19.fa.fai /dev/null > hg19.dict
```

**Comment by pkMyt1** [comment]
I will give that a check as well.  I made the dictionary but it has different chromosome naming than the BAM file.  1,2,3 instead of chr1, chr2, chr3.  HATCHet throws and error because of that.  For now I tweaked `def knownRegions(refdict, chromosomes):` so that it was consistent with the section that reads the BAM header for how it names the chromosomes.
