### ISSUE TITLE
Error using --chromosomes argument

### ISSUE THREAD

**Issue by wir963** [raphael-group/hatchet#163]
I am trying to reproduce the demo but running it step by step instead of using the ini script. I am using `hatchet 1.1.1`. When I pass the `--chromosomes chr22` argument to genotype-snps, hatchet parses this to be both chr2 and chr22. When I pass the `--chromosomes chr2` argument to genotype-snps, hatchet parses this to be only chr2. 

For example, the command
```
hatchet genotype-snps --normal data/normal.bam --reference data/hg19.fa --mincov 8 --maxcov 300 --chromosomes chr22 --outputsnps output/snps/
```
yields
```
[2022-Sep-08 13:04:54]('# Parsing the input arguments, checking the consistency of given files, and extracting required ', 'information\n')
	normal: ('/gpfs/gsfs9/users/Robinson-SB/HATCHet-demo/data/normal.bam', 'Normal')
	chromosomes: ['chr2', 'chr22']
	samtools: samtools
	bcftools: bcftools
	snps: None
	reference: data/hg19.fa
	j: 2
	q: 0
	Q: 11
	E: False
	mincov: 8
	maxcov: 300
	outputsnps: /gpfs/gsfs9/users/Robinson-SB/HATCHet-demo/output/snps
	verbose: False
```

If I pass the `--chromosomes chr18` argument to genotype-snps, hatchet parses this to be both chr1 and chr18.

This ends up being an issue because `read-counts` fails if no SNPs from the specified chromosomes are not found in the SNPs file (ex. `Chromosome chr2 not found in SNPs file`). 

Best, Welles

**Comment by vineetbansal** [comment]
Hi @wir963 - you're right again. The use-case we handled was for running against an `.ini` script for the demo. When you run this step (or any other that supports `--chromosomes`) directly from the command line, I do see the same buggy behavior as you mention here.

I have a fix ready to deploy for this and can make this available as `1.1.2` on our Github Releases page. I'm a little hesitant to put it up on `bioconda`, since you're now really exercising `HATCHet` and are likely to encounter other issues that I may have to address very soon anyway (plus there are a couple of pending comments from you in other issues that may still need addressing).  Will you be able to download the `1.1.2` release and compile/install it in your setup (compilation requires some Gurobi headers so if you haven't done it before it may be a bit complex).

**Comment by wir963** [comment]
Hey @vineetbansal,

I haven't downloaded and compiled/installed HATCHet yet but I'm happy to give it a try. I haven't played around with Gurobi but I've got plenty of experience on the command line/using man pages so I'm sure I'll be able to figure it out. Let me know when it's on the GitHub Release pages and I'll give it my best shot. 

Best, Welles

**Comment by vineetbansal** [comment]
Ok - the changes are now in the `master` branch, so you can clone the repository and install `HATCHet 1.1.2` directly. The basic idea is to set the `GUROBI_HOME` environment variable to where one can find Gurobi (9.0.2 against which `HATCHet` builds). Look at how we do this in our CI:

https://github.com/raphael-group/hatchet/blob/7d35a555cf914f92be14158a5bf7e58785b71b2f/.github/workflows/main.yml#L30

Followed by:
```
pip install .
```

You may or may not need the env var `CXXFLAGS` set to `-pthread` for the latter step depending on your OS settings.

**Comment by wir963** [comment]
Hey @vineetbansal , 

I was able to install the latest version of HATCHet. I've been able to run `genotype-snps` and `count-alleles` using the `--chromosomes` argument so thanks for fixing that bug. I'm still waiting to hear back from you on #150 but once I do, I'll try to run through the rest of the pipeline and report any problems. 

Best, Welles
