### ISSUE TITLE
help for result interpretation

### ISSUE THREAD

**Issue by SebastianHollizeck** [raphael-group/hatchet#18]
Hi,

I dont know if you guys would want this on github at all, but i have some questions, how to interpret the outputs, because its not a 100% clear to me from the manual.

FIrst of all, my data is far more fragmented on first glance than your example data. I attached the copy number plot so you know what I mean.
[intratumor-clones-totalcn.pdf](https://github.com/raphael-group/hatchet/files/5324556/intratumor-clones-totalcn.pdf)
Would you rerun the analysis with a bigger bin size, or change some parameter to discourage the fragmentation, or do you think this is real signal? 
The sequencing shown here is from 8 tumour samples at 160x depth.

following from that, i am not sure what the proportional plots mean. Is that the fraction of bins in that area that have that copy number? so if the region had sections with the hypothetical cns of 5,2,2,2,4 you would have 60%: 2 20%: 4 and 20%: 5 or am i missing something there?

And finally, what is the difference between the proportional plot and the mixture plot? shouldnt they be basically the same?
I would love to gain some insights into all of this.

Some additional questions:

I also realised, that my samples are assumed to be tetraploid
```
### SAMPLE: 26 -- PURITY: 0.707019 -- PLOIDY: 3.12095595261 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 41 -- PURITY: 0.2971019 -- PLOIDY: 3.26569623284 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 57 -- PURITY: 0.712802 -- PLOIDY: 3.12713806854 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 55 -- PURITY: 0.3873721 -- PLOIDY: 3.12282241734 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 47 -- PURITY: 0.4824277 -- PLOIDY: 3.1278291538 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 59 -- PURITY: 0.793201 -- PLOIDY: 3.25531305957 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 31 -- PURITY: 0.174453 -- PLOIDY: 3.86276716895 -- CLASSIFICATION: TETRAPLOID
### SAMPLE: 11 -- PURITY: 0.784387 -- PLOIDY: 3.10640781323 -- CLASSIFICATION: TETRAPLOID
```
But the sample is a human cancer, so it should be at least originally be diploid, what do I take away from this?

Also with other cn calling tools i have used, they did report possible alternate solutions for purity and ploidy, which obviously affect the calling quite heavily. I do have histological information about the cellularity of the sample, so I would love to see, if there might be another solution for a sample, which might be closer to what we already know of the sample.

**Comment by simozacca** [comment]
We would be very happy to assist you with your queries, and this will also help to improve the HATCHet's documentation.

Please find a comment to your queries here below:

1. Based on the information that your provided, it seems that your data are from whole-exome sequencing (WES). In this case, we [recommend to apply few changes](https://github.com/raphael-group/hatchet/blob/master/doc/recommendation_datatype.md) to the parameters of the pipelines to avoid confounding factors from off-targets data, in particular the following two changes proved to be sufficient when applying HATCHet on large cohorts of WES data.:
        - **Increase the bin size**, for example to 250kb, using the flag `-b` of the first step `binBAM`, i.e. `-b 250kb`
        - **Increase the minimum and maximum coverage for calling germline SNPs**, for example to 20 and 600, resp., using the flags `-c` and `-C` of the second step `deBAF`, i.e. `-c 20 -C 600`

2. The segmentation of your copy-number profile may look indeed suspicious and it may be due to the high level of noise in the data or to some failure in the BNPY clustering, as sometimes observed in noisy dataset. To address the first issue, please try to apply the changes recommended for WES data described in **(1)**. To address the second issue, please follow the [provided recommendations](https://github.com/raphael-group/hatchet/blob/master/doc/recommendation_clustering.md) and the [guided examples in the WES demo](https://github.com/raphael-group/hatchet/blob/master/examples/demo-WES/demo-wes.sh), to check whether there was a failure in clustering ("stripped effect") and apply proper corrections.

3. Concerning the evaluation plots, please see the related detailed description in the documentation of the step `BBeval` under `Detailed steps` [here](https://github.com/raphael-group/hatchet/blob/master/doc/doc_bbeval.md) and please let us know if you have further questions or something is not clear from those descriptions.

4. `CLASSIFICATION: TETRAPLOID` **does not mean that the samples have been assumed to be tetraploid, but it means that HATCHet predicted the occurrence of a whole-genome duplication (WGD) for the tumor clones in those samples** and the corresponding tumor is thus classified as tetraploid. If a tumor is classified as tetraploid, it means that a WGD occurred during tumor evolution, please read more details in the recently published version of the [HATCHet's article](https://doi.org/10.1038/s41467-020-17967-y).

5. HATCHet **does generate multiple solutions** according to every attempted number of clones and under the assumption that a WGD either occurred (tetraploid) or not (diploid). Each of these solutions is generated in the folder `results` and the details/format are reported in the documentation of the step `hatchet` under `Detailed steps` [here](https://github.com/raphael-group/hatchet/blob/master/doc/doc_hatchet.md). Please note that the files `chosen.diploid` and `chosel.tetraploid` represent the solutions chosen under the assumption of either the absence or presence of a WGD, and `best` indicates the final solution chose by HATCHet. In any case, you can select any pair of files `.bbc` and `.seg` corresponding to any solution and use the corresponding plotting modules (`BBot` and `BBeval`) to generate all the corresponding plots.

6. Please review all our recommendations [here](https://github.com/raphael-group/hatchet/blob/master/doc/doc_fullpipeline.md#recommendations), especially please review also the recommendations for quality control of the HATCHet's inference step [here](https://github.com/raphael-group/hatchet/blob/master/doc/recommendation_inference.md).

7. To have examples of running HATCHet on standard or noisy datasets, please review the [guided examples/demos](https://github.com/raphael-group/hatchet/blob/master/doc/doc_fullpipeline.md#demos), especially the guided examples for [WGS](https://github.com/raphael-group/hatchet/blob/master/examples/demo-WGS-sim/demo-wgs-sim.sh), [noisy WGS](https://github.com/raphael-group/hatchet/blob/master/examples/demo-WGS-cancer/demo-wgs-cancer.sh), and [noisy WES](https://github.com/raphael-group/hatchet/blob/master/examples/demo-WES/demo-wes.sh).

Please do let us know if you have any further questions or if any of these comments is not fully clear,
Thank you

**Comment by SebastianHollizeck** [comment]
Hi,

thanks so much for the feedback.

I was sure i had written this, but it is actually WGS with 160x, so its a huge amount of data. And i have a few more to analyse, so i want to get this right before i do this for the rest, so i really appreciate the help.

I understood that the first step would be to check the clustering from the bb_clustered file.
Which in my case i think clearly does not show distinct clusters, so that needs adjusting. But in contrast to the images in your demo, I dont see how I would adjust the parameter in a sensible way.
I attached the image (converted to png), so maybe you could give me an educated guess. 
![bb_clustered](https://user-images.githubusercontent.com/4959657/95165099-0bba3000-07f7-11eb-8f7d-061c0a8629f6.png)

**Comment by simozacca** [comment]
A WGS dataset with 160x is very interesting! However, despite the kind of sequencing, the minimum/maximum number of sequencing reads for SNP calling should be adjusted according to the sequencing coverage of the matched-normal sample. Thus, if the sequencing coverage of the matched-normal sample is also 160x, I would recommend to apply the changes for `-c` and `-C` described in **(1)** above. We will aim to add an automatic adjustment in the next release. Moreover, if you would like to reduce the variance and uncertainty in your data and you do not mind a slightly lower resolution for copy numbers, it may worth to slightly increase the bin size to, for example to 100kb, 150kb, or 200kb. In the HATCHet's article, we used 50kb for all analyzed WGS datasets (and 250kb for WES) but we noted that higher bin sizes generally result in lower noise in the resulting data.

I would be very happy to provide support in the interpretation of the bb_clustered file:

1. Could you please confirm the command that you used to generate the plot? In particular, did you use the flag `-tS 0.01`? Often, when we consider many samples, there could be many small clusters that obscure the plot because their number is much higher than the available colors; thus the flag `-tS 0.01` allows to only plot the major clusters, and you can even increase the value to 0.02, 0.03, ... if needed. Could you please run the following and provide the corresponding plot:
```
python2 -m hatchet BBot  -c CBB ${BBC}bulk.bbc -tS 0.03
```

2. Based on the size of the major clusters in your example, it may worth to already increase the value of the `cluBB` parameters `-tB` and `-tR` to higher values, for example `-tB 0.05` and `-tR 0.35`

Thank you

**Comment by SebastianHollizeck** [comment]
Hi,

I am not too worried about the size of the binning, as we do work with clinical samples, where the purity might be lower, so i would rather have fairly confident calls.
The normal "only" has a coverage of 100x and only the tumour samples were sequenced with 160x, so if the variants are selected from the normal, then i think the 300 max coverage would be appropriate?

It seems my workflow ate that input, and it was run without that threshold.
so here the plot with the threshold which looks much cleaner
![bb_clustered](https://user-images.githubusercontent.com/4959657/95284485-0bc73800-08aa-11eb-8156-de4e45f3a113.jpg)

Do you still think i should rerun the clustering?

Thanks so much for your help

**Comment by simozacca** [comment]
Yes, if the matched-normal sample has a sequencing coverage of 100x, I would use something like `-c 10` and `-C 300`. Also, if you do not mind bin size, I would then definitely try a higher bin size, for example of `-b 200kb` (this will also help with the other issue described here below).

Thank you for generating the new RDR-BAF plot (i.e. bb_clustered). From this new version, it looks like that there is some sign of overclustering (splitting apart too many clusters): for example, light green and light blue clusters are likely part of the same cluster as they are always very close to each other in **every** sample. This overclustering seems to be due to the presence of overdispersion in RDR (x-axis) in one sample, i.e. sample 59: you can easily note this by the fact that all clusters in sample 59 have a "longer" or "stretched" shape. Therefore, I would apply the changes suggested above for `-tR` in order to merge such clusters; for example I would try `-tR 0.35` or `-tR 0.4` according to the [recommendations](https://github.com/raphael-group/hatchet/blob/master/doc/recommendation_clustering.md).

Moreover, please note that, in addition to the parameters of HATCHet above, you can try to improve the parameters of BNPY itself, if you would like to tune as much as possible the parameters to your kind of data. Specifically, the authors of BNPY recommend to try different values for `-K` (the initial guess for the number of clusters, it is 15 by default and higher values like 30, 50, .... allow to identify smaller clusters) and `-sf` (the parameter that control the sensitivity, the default value is 0.01 and smaller values like 0.001, 0.0001,.. will also allow to separate smaller clusters). More details about this are also reported in the [recommendations](https://github.com/raphael-group/hatchet/blob/master/doc/recommendation_clustering.md).

**Comment by SebastianHollizeck** [comment]
Hi,

its me again, with some more results from the analysis with the changed parameter.
As suggested, i ran the binning and baf calculation again with 200kb bins and a snp detection range from 10-300x 

Then I adjusted the clustering to give me bigger clusters -sf 0.1 , to restart the process more often (for bigger chance for a global maximum) and with a bigger threshold for the read depth ratio -tR 0.5
`python2 -m hatchet cluBB $bbDir"/bulk.bb" -o $bbcDir"/bulk.seg" -O $bbcDir"/bulk.bbc" -e 12 -tB 0.04 -tR 0.5 -d 0.08 -R 40 -sf 0.1 -K 15 -v`

and then visualised the clustering with 
`python2 -m hatchet BBot -c CBB --figsize 8,4.5 $bbcDir"/bulk.bbc" -x $analysisDir -tS 0.01`
So here is how it looks 
[bb_clustered.pdf](https://github.com/raphael-group/hatchet/files/5362468/bb_clustered.pdf)
and I left it as a pdf this time, because there is some time delay when opening the file, which leads to the individual colours being added one after another and there it looks, like there is still some substantial overlap between the blue and the orange and some other minor clusters. This could be due to the visualisation only, but it does make me worry.

It also doesnt look perfect with the clustering yet, as a human, i would probably still assign clusters differently, but it is very hard to judge, if this is now better than the previous version.

What do you think?

**Comment by simozacca** [comment]
I think this is a very good step forward, but we can definitely improve it; the large variance of 1/2 samples makes the fitting more challenging but we will find a good compromise.

Could you please try to run the following commands? I think that it's worth trying to form smaller clusters with BNPY (i.e. `-sf 0.001`) and then merge those (i.e. `-tB 0.02 -tR 0.8` or `-tB 0.03 -tR 0.8`)

```
python2 -m hatchet cluBB $bbDir"/bulk.bb" -o $bbcDir"/bulk.seg" -O $bbcDir"/bulk.bbc" -e 12 -tB 0.02 -tR 0.8 -d 0.08 -R 40 -sf 0.001 -K 50 -v
python2 -m hatchet BBot -c CBB $bbcDir"/bulk.bbc" -x $analysisDir -tS 0.01
``` 

Also, we are sorry for the issues with PDF, and we will fix it soon by plotting in PNG instead. For now, you could fix it if you have `convert` by using the following to convert it to PNG:
```
convert -trim -density 600 bb_clustered.pdf bb_clustered.png
```

**Comment by SebastianHollizeck** [comment]
Hey,

There i am again. This is the respective output from the workflow
```
Mon Oct 19 09:32:32 AEDT 2020: - Start clustering
[2020-Oct-19 09:33:08]# Parsing and checking input arguments
[2020-Oct-19 09:33:08]# Reading the combined BB file
[2020-Oct-19 09:33:10]# Format data to cluster
[2020-Oct-19 09:33:10]# Clustering bins by RD and BAF across tumor samples
[2020-Oct-19 09:33:10]## Loading BNPY
[2020-Oct-19 09:33:19]## Clustering...
[2020-Oct-19 12:39:33]# Refining clustering using given tolerances
[2020-Oct-19 12:40:21]The number of clusters have been reduced from 65 to 36 with given tolerances
[2020-Oct-19 12:40:21]# Writing BBC output with resulting clusters
[2020-Oct-19 12:40:22]# Segmenting bins
[2020-Oct-19 12:40:23]# Determining the largest cluster as diploid or tetraploid and rescaling all the clusters inside the threshold accordingly
[2020-Oct-19 12:40:23]# Writing REF output with resulting segments
Mon Oct 19 12:40:24 AEDT 2020: - End clustering
```

And then plotting 
```
Mon Oct 19 12:40:24 AEDT 2020: - Start plotting
# Parsing and checking input arguments
# Reading input BBC file
# Parsing and checking input arguments
# Reading input BBC file
# Parsing and checking input arguments
# Parsing and checking input arguments
# Reading input BBC file
# Reading input BBC file
# Parsing and checking input arguments
# Reading input BBC file
# Bin's clusters are selected accordingly to the provided thresholds
# [CRD] Plotting the clustered read-depth ratio (RDR) for each sample in /home/shollizeck/test_hatchet//analysis/readdepthratio_clustered.pdf
## Selected clusters: 
1:	SIZE= 638.0,	# CHRS= set(['chr5', 'chr4', 'chr2', 'chr1'])
26:	SIZE= 2973.0,	# CHRS= set(['chr7', 'chr6', 'chr4', 'chr3', 'chr2', 'chr1', 'chr21', 'chr9', 'chr12', 'chr11', 'chr17', 'chr16', 'chr20', 'chr14', 'chr22', 'chr19', 'chr18'])
59:	SIZE= 1537.0,	# CHRS= set(['chr6', 'chr5', 'chr4', 'chr1', 'chr13', 'chr12', 'chr18'])
22:	SIZE= 974.0,	# CHRS= set(['chr5', 'chr10', 'chr4'])
55:	SIZE= 1055.0,	# CHRS= set(['chr13', 'chr12', 'chr11', 'chr10', 'chr17', 'chr16', 'chr15', 'chr14', 'chr19', 'chr18', 'chr22', 'chr20', 'chr21', 'chr7', 'chr6', 'chr5', 'chr4', 'chr3', 'chr2', 'chr1', 'chr9', 'chr8'])
57:	SIZE= 1567.0,	# CHRS= set(['chr6', 'chr5', 'chr3', 'chr2', 'chr1', 'chr8', 'chr13', 'chr12', 'chr11', 'chr10', 'chr22', 'chr20', 'chr21', 'chr19', 'chr18'])
30:	SIZE= 1368.0,	# CHRS= set(['chr7', 'chr6', 'chr2'])
39:	SIZE= 4477.0,	# CHRS= set(['chr6', 'chr5', 'chr4', 'chr3', 'chr2', 'chr1', 'chr8', 'chr12', 'chr11', 'chr10', 'chr22', 'chr16', 'chr20', 'chr21', 'chr19'])
35:	SIZE= 1204.0,	# CHRS= set(['chr6', 'chr3', 'chr1', 'chr8', 'chr12', 'chr10'])
60:	SIZE= 1755.0,	# CHRS= set(['chr7', 'chr6', 'chr3', 'chr1', 'chr9', 'chr8', 'chr14'])
4:	SIZE= 731.0,	# CHRS= set(['chr7', 'chr6', 'chr5', 'chr4', 'chr3', 'chr2', 'chr1', 'chr8', 'chr13', 'chr12', 'chr11', 'chr16', 'chr18'])
15:	SIZE= 2336.0,	# CHRS= set(['chr7', 'chr6', 'chr3', 'chr1', 'chr9', 'chr13', 'chr16', 'chr20', 'chr14', 'chr19'])
# [BAF] Plotting B-allele frequency (BAF) for all samples in /home/shollizeck/test_hatchet//analysis/ballelefrequency.pdf
# [BB] Plotting RDR-BB for all samples in /home/shollizeck/test_hatchet//analysis/bb.pdf
# [RD] Plotting read-depth ratio (RDR) for all samples in /home/shollizeck/test_hatchet//analysis/readdepthratio.pdf
# [CBB] Plotting clustered RDR-BB for all samples in /home/shollizeck/test_hatchet//analysis/bb_clustered.pdf
[omitted due to parallelised ouput]
Mon Oct 19 12:43:53 AEDT 2020: - End plotting
```

with this 
![bb_clustered](https://user-images.githubusercontent.com/4959657/96679980-63909380-13c0-11eb-8386-8e557f12de7c.png)
As the outcome of the clustering

**Comment by simozacca** [comment]
The clustering seems better and it captures differences across samples; could you please plot with `-tS 0.03` to remove some color overlapping so that we can give a more precise answer? Thank you.

**Comment by SebastianHollizeck** [comment]
absolutely i can 
![bb_clustered](https://user-images.githubusercontent.com/4959657/96821288-4cf74480-1473-11eb-85d8-2fb2eab358bf.png)

**Comment by simozacca** [comment]
I think that the clustering is pretty good to continue the inference with HATCHet. Also, I would recommend to use `-d 0.07` in `cluBB` to guarantee the best BAF correction.

Since the results look pretty good, I am going to close the issue but please feel free to re-open it if you have further questions
