### ISSUE TITLE
Library nomalization

### ISSUE THREAD

**Issue by chaos66ren** [raphael-group/hatchet#20]
Have this software performed library normalization before or after computing the LogR value? If not, would it affect the clustering result since this software use both LogR and BAF value to cluster bin? 

![image](https://user-images.githubusercontent.com/20034376/96240860-02d61500-0fd4-11eb-988c-b537b2a91ca8.png)

**Comment by simozacca** [comment]
Thank you for the interest in HATCHet, we would be happy to provide more information.

There is a misunderstanding of the global clustering in the reported example: genomic regions in the same cluster does **not** mean that those genomic regions have the **same** copy number in **all** samples, instead it means that, in each sample and in each tumor clone the genomic regions have the same copy number, which can be different in distinct samples and clones.

In your specific example, all the genomic regions of chr19p have been clustered together because HATCHet believes that these regions have the same copy number in each sample: that is, under the assumption that a WGD did not occur, these regions likely have copy number 2 in the first sample and copy number 1 in the second sample. For more details of the global clustering, please refer to the [published article](https://www.nature.com/articles/s41467-020-17967-y) and its supplement. Please note that the colors of chr19p and chr19q are different, green vs. teal, and if you do not like the color palette please use another one from those [available](https://github.com/raphael-group/hatchet/blob/master/doc/doc_bbot.md).

Importantly, at this stage, RDR values across different samples are **not** comparable because the RDR is affected by sample-specific constant factors: for example, the total number of sequenced reads per sample and tumor ploidy, which can be different across samples. These sample-specific factors are corrected during the `HATCHet` step, which follows the clustering. For a formal and mathematical detailed explanation of these factors, please refer to Supplementary Methods 1 of the [published article](https://www.nature.com/articles/s41467-020-17967-y).

The global clustering does not assume that regions in the same cluster must have the same RDR in every sample, thus it is not affected by these factors. Specifically, linear scaling of RDRs for constant factors will not change the inference. Given the clustering (which looks pretty good according to our [QC](https://github.com/raphael-group/hatchet/blob/master/doc/recommendation_clustering.md)), you will see that HATCHet will correctly infer that chr19q has the different expected copy numbers in the two samples, with two or more distinct clones present in the two different samples.

Since the behavior is as expected, we are closing the issue, but please feel free to ask further questions if anything is not clear.
