### ISSUE TITLE
deal with primary/met tumor-only samples 

### ISSUE THREAD

**Issue by qindan2008** [raphael-group/hatchet#25]
I have 10 pairs of primary/met samples from 10 patients, but none of them have normal samples.
Is hatchet able to be used in this situation?

Thanks

**Comment by simozacca** [comment]
Thank you for yout interest in HATCHet!

HATCHet requires a matched-normal sample for every patient (note that HATCHet jointly analyzes only samples from the same patient), especially for the identification of heterozygous germline SNPs. There is however a way to get around this requirement by simulating a matched-normal sample; this can be achieved in two steps:

1. Identify putative heterozygous germline SNPs by identifying heterozygous variants from standard SNP databases (e.g. dbSNP, 1000GP, HRC< etc.) that are also present in the tumour samples (this can be done by using BCFtools by interrogating the tumour samples only in the given SNP positions).

2. Use [MASCoTE](https://github.com/raphael-group/mascote) to simulate a matched-normal sample by providing in input the list of heterozygous SNPs identified before in **(1.)** and by specifying the flag `-e` of the `mascote` step in order to include all these variants. Importantly, note that you can achieve this without running the mixing step `MixBams.py` and by specifying 0 tumour clones.

This approach has already been tested by a few labs and it worked smoothly with successful results.

Please let us know if this may work for you and if you have any further questions.

**Comment by simozacca** [comment]
We assume that the issue has been answered; please feel free to re-open if there are further questions.

**Comment by kristianunger** [comment]
That seems to be extremely helpful as I have exactly the same scenario - primary tumors/metastases without matched normals. Would it be possible to be even more concrete how I would identify the heterogenous SNPs from the tumor samples? Would I match the dbSNP DB with the Mutect2-vcfs?

**Comment by kristianunger** [comment]
It seems I managed to do myself.

**Comment by tahashmi** [comment]
Hi @kristianunger, wondering if you have some script or easy steps on-hand to repeat for Tumor-only mode? Thanks.
