### ISSUE TITLE
docker or conda version of hatchet

### ISSUE THREAD

**Issue by 2236529177** [raphael-group/hatchet#27]
hi, is there a docker or conda version of hatchet. if so, is there some command about how to use  hatchet in such situation,
thanks a lot

**Comment by simozacca** [comment]
Thank you for the interest in HATCHet!

Unfortunately there is no docker due to license restrictions with Gurobi. On the other hand, we are planning to release a conda version of HATCHet soon but we are first waiting for the completing of the same process for [BNPY](https://github.com/bnpy/bnpy) together with its transition to Python 3. We will update this issue once the conda version will be released.
