### ISSUE TITLE
None potential neutral cluster found with given parameters!

### ISSUE THREAD

**Issue by ahgillmo** [raphael-group/hatchet#49]
Hello, 
I am trying to run Hatchet solve on the bulk.bbc and bulk.seg. 

The code I am trying to execute is: python2 /hatchet/bin/HATCHet.py /hatchet/build/solve -i bulk -n2,8 -p 400 -v 3 -r ${RANDOM} &> >(tee >(grep -v Progress > hatchet.log))

The error I keep getting is:
ValueError: None potential neutral cluster found with given parameters!

Is this problem due to previous steps (eg. clubb.py) or the parameters being fed into the hatchet solver?

Any help would be appreciated,
Aaron

**Comment by simozacca** [comment]
The HATCHet step `HATCHet.py` checks that there is at least one cluster with BAF nearly equal to 0.5 in all samples (with a tolerance determined by the parameter `-td` or `maxneutralshift` which is 0.01 by default). In this case, HATCHet is complaining that such cluster has not been found.

This should not happen because the same check should occur at the earlier clustering step `cluBB`, which also rescale at least one cluster to have BAF exactly 0.5 in all samples. Could you please confirm the outcome of the `cluBB` step or any change has been applied? Also, could you please paste here the content of the file `bulk.seg`?

**Comment by ahgillmo** [comment]
Thank you for the reply

For running clubb.py my command was 
python2 /home/ahgillmo/hatchet/utils/cluBB.py bulk.bb -by ${bnpy} -o bulk.seg -O bulk.bbc -e ${RANDOM}

The output of running the above command is: There are no errors or warnings and both bulk.bbc and bulk.seg is generated. 

[2021-Mar-25 23:36:51]# Parsing and checking input arguments
[2021-Mar-25 23:36:51]# Reading the combined BB file
[2021-Mar-25 23:36:53]# Format data to cluster
[2021-Mar-25 23:36:53]# Clustering bins by RD and BAF across tumor samples
[2021-Mar-25 23:36:53]## Loading BNPY
[2021-Mar-25 23:37:04]## Clustering...
[2021-Mar-25 23:40:40]# Writing BBC output with resulting clusters
[2021-Mar-25 23:40:41]# Segmenting bins
[2021-Mar-25 23:40:43]# Writing REF output with resulting segments

When I open the seg file, I don't see any group that has been set to 0.5 in the bulk.seg file

[bulk.seg.txt](https://github.com/raphael-group/hatchet/files/6209604/bulk.seg.txt)

**Comment by simozacca** [comment]
@ahgillmo This is due to the missing parameter `-d`, could you please try to add `-d 0.06` for example? We are sorry for this need and we will add a default value.

@vineetbansal We should add a default value for `diploidbaf` in `cluBB` within `hatchet.ini`; for example we can add `0.06` to start.

@mmyers1 Could you please suggest the best default value for `-d` in `cluBB` according to the new implementation? Also, could you please give a quick look to the example posted above and suggest why we do not see values pretty close to 0.5? Is this likely to the data or the new implementation for BAF estimation?

**Comment by mmyers1** [comment]
@simozacca @vineetbansal 
The BAF estimation on master has not (yet) been changed, neither has the balanced BAF scaling with `-d`. The issue above is likely due to the known bias with the minimum estimator for the BAF. I would recommend the default be set to `0.1` which should at least produce some balanced cluster for most input.

**Comment by ahgillmo** [comment]
I changed the -d parameter to 0.1 as per @mmyers1  and still noted that it failed. When I increased the value to 0.12 it ended up working. I think this has addressed the problem I was having.

**Comment by simozacca** [comment]
I have added a default value of 0.1 for `-d` in `cluBB`:
https://github.com/raphael-group/hatchet/blob/78b847c37290a56cb31e8380d3be3884579f993c/src/hatchet/hatchet.ini#L56

 Please feel free to re-open the issue in case of additional concerns.

**Comment by miachom** [comment]
Hi, 
I am also facing the same issue when I tried to run with the example data and hatchet v1.1.2. I kept changing `diploidbaf = 0.1 or 0.12` and also with default `diploidbaf = 0.08` it's giving me the same as `ValueError: No potential neutral cluster has been found within the given threshold 0.1!`

I am not sure what's going on. Could you please help?
Thanks.
