### ISSUE TITLE
Compatibility with PhyloWGS

### ISSUE THREAD

**Issue by ad2021** [raphael-group/hatchet#51]
Hi,

I am working with a dataset with high aneuploidy and I was hoping to use your tool in combination with https://github.com/morrislab/phylowgs. (I tried battenberg before, but I think there may be too much noise to compare CNA calls cross-sample)

Can the output from from hatchet be made similar to the [_subclones.txt](https://github.com/Wedge-lab/battenberg) files that [phylowgs](https://github.com/morrislab/phylowgs/tree/master/parser) uses?

Thank you

**Comment by simozacca** [comment]
Yes, HATCHet's output can be converted to an output similar to the one of Battenberg by:
1. Scaling the proportions of tumour clones by the corresponding tumor purity;
2. Combining in every segment the proportions of clones with the same allele-specific copy numbers.

For example, the following segment:
```
chr2   0    10000000     SAMPLE    1|1   0.1    2|1   0.3    2|1   0.5    2|0   0.1
```
will be converted to a Battenberg segment with copy numbers: `2|1` in tumor proportion `(0.3 + 0.5) / 0.9 = 0.89` and `2|0` in tumor proportion `0.1 / 0.9 = 0.11`. All the other temporary and Battenberg-specific values in `_subclones.txt` should be estimated from this conversion or set at some default values, as PhyloWGS should only use the inferred copy numbers and corresponding proportions. This conversion should be easily implementable in data-processing languages like Python or R since HATCHet's output are standard tab-separated dataframes. Alternatively, you could request PhyloWGS maintainers whether there is the possibility to include HATCHet's output in the supported formats for copy numbers. 

Please feel free to follow up on this issue in case of further questions.
