### ISSUE TITLE
Samtools: libcrypto.so.1.0.0: cannot open shared object file

### ISSUE THREAD

**Issue by prateek-anand** [raphael-group/hatchet#67]
Samtools was not being installed properly using conda:

    /usr/local/bin/samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

I believe this issue was addressed in [#13958](https://github.com/bioconda/bioconda-recipes/issues/13958), but none of the fixes seemed to work for me except changing the order of the channels in my Dockerfile:

    RUN conda create -qy -p /usr/local \
        -c conda-forge \
        -c bioconda \
        -c defaults \
        hatchet==${HATCHET_VERSION}

The documentation states:

    conda config --add channels defaults
    conda config --add channels bioconda
    conda config --add channels conda-forge

Please let me know if there's a different way to approach this. Thanks.

Edit: When using hatchet run hatchet.ini, in addition to reference.dict, I also needed the .bai files for each bam file in the same directory. This wasn't mentioned in the script README so it might help to clarify.

**Comment by vineetbansal** [comment]
Hi @prateek-anand - I might be mistaken, but what you're doing in your Dockerfile with specifying multiple channels on the command line (which causes the first channel where a package is found to be preferred over others) will have the same effect as the documented way (which causes new channels to be added to the start of the channel list, prioritizing them over others).

**Comment by prateek-anand** [comment]
Thanks for the response. If they have the same effect, is it okay then to keep the channels in the order I mentioned, or will it affect the program in any way? I'm unable to add them as specified in the documentation due to this error. I'm also wondering if this has affected anyone else.

**Comment by vineetbansal** [comment]
A small clarification - when you say "I'm unable to add them as specified in the documentation due to this error." - the error you've pasted here will of course happen when you try to invoke `samtools` (by itself or as part of running some HATCHet step that uses it), so *after* installation of HATCHet, but of course the `conda config --add channels` steps are to be taken *before* any installation of HATCHet is attempted (and the current documentation does mention this).

In all of our tests, we install it using the documented steps (in a brand new conda environment) and have not encountered any errors (and have heard no complaints from users). In any case, the recommended order of channels (which bioconda recommends too) is only to successfully install HATCHet, and has no effect once the package is installed. So if you're able to install it using the way you list here, that's perfectly fine too.

**Comment by prateek-anand** [comment]
I see, thank you!
