### ISSUE TITLE
The regions provided for chromosome are non-disjoint or a region start is greater than corresponding region end

### ISSUE THREAD

**Issue by proteinosome** [raphael-group/hatchet#7]
Hi, thanks for the software. I've been trying to run this on a whole exome samples with a exome bed region from hg38. There's currently a bug in the bed file verification whereby if you use bed file with "chr" naming convention (GRCh37 and hg38), the regions are read in as characters and the sort function will not work properly for parseRegions function in ArgParsing.py script. This will throw out the error (Due to the algorithm sorting the keys as string rather than numerics):

`The regions provided for chromosome are non-disjoint or a region start is greater than corresponding region end`

To solve this, I changed the append function from:
`res[chro].append((split[1], split[2])) `

to:
`res[chro].append((int(split[1]), int(split[2]))) `

And it seems to be running fine now. I will update further if there's more issues!

**Comment by simozacca** [comment]
Thank you for identifying this bug!
This is indeed a bug of the code when using a region file and the proposed solution is a proper solution that I will integrate soon. However the bug is not related to the ordering of the chromosomes, rather it is related to the START and END positions that are read as strings instead of integers and this is likely the reason of the error.

Providing a BED file to specify the exome regions is indeed the proper procedure to apply when analyzing WES data. However I would like to mention for completeness that another possibility to analyze WES data is to simply increase the minimum number of reads for identifying SNPs in the `deBAF` step. In fact, off-target regions will be automatically discarded since their SNPs are not covered by a sufficiently high number of reads.

I keep the issue open until the integration of the correction is finalized.
Thank you

**Comment by proteinosome** [comment]
Hi @simozacca yes you're right it's because of the comparison between strings rather than sorting, I stand corrected. Thanks for the tips on setting minimum number of reads as well. I wonder what will the overhead be compared to using a region bed file however?

**Comment by simozacca** [comment]
Yes, the running time of `binBAM` will increase, however we do not expect a significant impact on the total running time from our experience. If you have confidence in the list of the genomic regions that probably remains the preferred way.

**Comment by proteinosome** [comment]
After changing the parseRegions function, HATCHet was able to continue running without the error in the title. However, I am getting "The selected SNPs are not covered in the tumors!" error. It appears that the program was unable to output any SNPs (selectedSNPs.csv is empty). I will try to debug when I have more time, but I am not sure if this could be a similar issues? (using chromosomes with the "chr" convention). Thank you!

**Comment by simozacca** [comment]
The current version of HATCHet is now properly supporting BED files that specifies genomic regions (especially useful for analysis of WES data); in particular, several fixes have been applied to correct the handling of BED files and these new fixes should also result in a significant improvement of running time.

Please let us know if you can test this new version. Also notice that the new version provide the reference genome directly to `binBAM`; as such please correct the script `runHATCHet.sh` accordingly as shown [here](https://github.com/raphael-group/hatchet/blob/master/script/runHATCHet.sh) and in the [tutorial](https://github.com/raphael-group/hatchet/blob/master/doc/doc_runhatchet.md).

**Comment by proteinosome** [comment]
Thank you very much for the quick response and bug fix! I will definitely test it out and let you know if there's any issue, thank you.
