### ISSUE TITLE
Fixing Normal Clone Proportion

### ISSUE THREAD

**Issue by jdm204** [raphael-group/hatchet#88]
In scenarios when the normal clone proportion is known (i.e pathologist quantified), is it possible to incorporate this knowledge and fix this value for the 'compute-cn' step? I've been playing with parameters but so far all returned solutions have unrealistic normal clone proportions (>0.4 when tumour purity is ~80%).

Thanks for maintaining hatchet!

**Comment by simozacca** [comment]
The current version of HATCHet does not allow the user to directly fix the value of tumor purity, because tumor purity and ploidy are dependent and are estimated jointly. However, since tumor purity and ploidy are jointly estimated, you could consider the different inferred solutions, especially diploid vs tetraploid, and you could choose the solution that best fit your prior information. For example, if the best diploid solution reports a tumor purity of ~80%, while the best tetraploid solution has a tumor purity of ~60%, you could choose the best diploid solution despite the final choice made by HATCHet. Please check the related guidances for investigating all the different inferred solutions [here](http://compbio.cs.brown.edu/hatchet/doc_compute_cn.html).

Moreover, while you cannot directly fix tumor purity, you can however tune the parameters that will influence this inference. Therefore, you could tune the parameters in order to best fit (in either the diploid or tetraploid solution) your prior information. Please read the related recommendations for such tuning [here](http://compbio.cs.brown.edu/hatchet/recommendation_inference.html).

Please let us know if you have any further question.

**Comment by simozacca** [comment]
We assume that the issue has been solved. However, please feel free to re-open the issue in case of further questions.
